trigger:
- main  # Trigger the pipeline when changes are made to the main branch

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: GitHubToAzureSync  # Reference the variable group containing the PAT

steps:
- checkout: self
  fetchDepth: 0  # Ensure the full history is fetched

- script: |
    # Set up Git configuration
    git config --global user.name "bobiasg"
    git config --global user.email "bobiasg@gmail.com"

    # Add Azure Repos as a remote using PAT for authentication
    git remote add azure https://$(AZURE_DEVOPS_PAT)@bobiasg.visualstudio.com/Mini_CRM/_git/Mini_CRM

    # Fetch all branches from GitHub
    #git fetch origin

    # Sync main branch
    git checkout main
    git push azure main --force

  displayName: 'Sync GitHub to Azure Repos'
