# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pr: none



pool:
  vmImage: ubuntu-latest

variables:
  IMAGE_NAME: 'bobiasg/sms-management'

stages: 
- stage: CheckImageExist
  displayName: check image exists in docker hub
  jobs:
  - job: SetDockerImageTag
    displayName: 'Get Git Info'
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
    steps:
    # - checkout: self
    #   fetchDepth: 1      
    #   displayName: 'Checkout repository'

    - script: |
        echo "##[section]Determining image tag"
        echo "commit hash: $(Build.SourceVersion)"
        
        # SHORT_GIT_HASH=$(git rev-parse --short HEAD)
        # Fetch the full commit hash of the HEAD
        FULL_GIT_HASH=$(git ls-remote $(Build.Repository.Uri) HEAD | cut -f 1)
        # Truncate the full hash to get a short hash (first 7 characters)
        SHORT_GIT_HASH=${FULL_GIT_HASH:0:7}

        IMAGE_TAG="sha-$SHORT_GIT_HASH"
        echo "ImageApp: $(IMAGE_NAME):$IMAGE_TAG"
        echo "##vso[task.setvariable variable=IMAGE_TAG;isOutput=true]$IMAGE_TAG"
      displayName: 'Set Docker Image Tag'
      name: ImageTagInfo
  
  - job: CheckImage  
    displayName: "Check image exists before deploy"
    dependsOn: SetDockerImageTag # Replace with the actual job name that sets IMAGE_TAG
    variables:
      IMAGE_TAG: $[ dependencies.SetDockerImageTag.outputs['ImageTagInfo.IMAGE_TAG'] ]  
    steps:
    - checkout: none
    - task: Docker@2
      inputs:
        containerRegistry: 'DockerHub-Bobiasg'
        command: 'login'
   
    - script: |
        echo "image name: $(IMAGE_NAME), tag: $(IMAGE_TAG)"
        IMAGE_APP="$(IMAGE_NAME):$(IMAGE_TAG)"
        echo "Check $IMAGE_APP exists"

        if docker pull "$IMAGE_APP" &> /dev/null; then
          echo "Docker image $IMAGE_APP exists on Docker Hub."
        else
          echo "Docker image $IMAGE_APP does not exist on Docker Hub."
          echo "##vso[task.setvariable variable=IMAGE_TAG_DOES_NOT_EXIST;isOutput=true]true"
        fi
      name: CheckImageExist    

  - job: BuildImage 
    displayName: "Build image and push to docker hub"
    dependsOn: [CheckImage, SetDockerImageTag]
    condition: eq(dependencies.CheckImage.outputs['CheckImageExist.IMAGE_TAG_DOES_NOT_EXIST'], true)
    variables:
      IMAGE_TAG: $[ dependencies.SetDockerImageTag.outputs['ImageTagInfo.IMAGE_TAG'] ]  
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'DockerHub-Bobiasg'
        repository: 'bobiasg/sms-management'
        command: 'buildAndPush'
        Dockerfile: '**/dockerfile'
        tags: |
          $(IMAGE_TAG)

- stage: ApprovalStage
  jobs:
  - deployment: WaitForApproval
    displayName: "Manual Approval if Triggered by Webhook"
    environment: webhook
    condition: eq(variables['Build.Reason'], 'Webhook') # Adjust this condition based on your scenario
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo "Approved to proceed"

- stage: Deploy
  condition: and(succeeded('ApprovalStage'), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  dependsOn: CheckImageExist
  variables:
      IMAGE_TAG: $[ stageDependencies.CheckImageExist.SetDockerImageTag.outputs['ImageTagInfo.IMAGE_TAG'] ]  
  displayName: 'Staging Deployment'
  jobs:
    - deployment: DeployToStaging
      environment: staging
      strategy:
        runOnce:
          deploy:
            steps:
              - task: AzureWebAppContainer@1
                inputs:
                  azureSubscription: 'Azure subscription 1 (a99f60cb-60c3-451b-b209-66fbbbe9f4c6)'
                  appName: 'minicrm-bobiasg-docker2'
                  containers: "$(IMAGE_NAME):$(IMAGE_TAG)"



