# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pr: none

pool:
  vmImage: ubuntu-latest

variables:

stages: 
- stage: Check Image
  jobs:
  - job: GetGitInfo
    displayName: 'Get Git Info'
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
    steps:
    - checkout: self
      displayName: 'Checkout repository'

    - script: |
      echo "##[section]Determining short Git hash"
      SHORT_GIT_HASH=$(git rev-parse --short HEAD)
      IMAGE_APP="bobiasg/sms-management:sha-$SHORT_GIT_HASH"
      echo "Short Git Hash: $SHORT_GIT_HASH"
      echo "##vso[task.setvariable variable=ShortGitHash]$SHORT_GIT_HASH"
      echo "##vso[task.setvariable variable=$IMAGE_APP"

  - job: CheckImage  
    displayName: "Check image exists before deploy"
    steps:
    - task: Docker@2
      inputs:
        command: 'login'
        

    - script: |
      echo "Check $(ImageApp) exists"
      if docker pull "$(ImageApp)" &> /dev/null; then
        echo "Docker image $(ImageApp) exists on Docker Hub."
      else
        echo "Docker image $(ImageApp) does not exist on Docker Hub."
        exit 1
      fi
   
- stage: Deploy
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    displayName: 'Dev Deployment'
    jobs:
      - deployment: DeployToStaging
        environment: staging
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureWebAppContainer@1
                  inputs:
                    azureSubscription: 'Azure subscription 1 (a99f60cb-60c3-451b-b209-66fbbbe9f4c6)'
                    appName: 'minicrm-bobiasg-docker2'
                    containers: '$ImageApp'



