name: Continuous Deployment

on:
  workflow_dispatch:

jobs:
  approve:
    runs-on: ubuntu-latest
    environment: staging # This environment requires manual approval in the repo settings
    steps:
      - name: Wait for approving
        uses: trstringer/manual-approval@v1.9.0
        with:
          approvers: bobiasg
          
